name: Criar release do engine

on:
  push:
    paths:
      - "VERSION"
    branches:
      - main
  workflow_dispatch:

jobs:
  release-engine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ler versÃ£o do engine
        id: version
        run: |
          CODENAME=$(awk '{print $1}' VERSION)
          VERSION=$(awk '{print $2}' VERSION)
          echo "codename=$CODENAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Ler CHANGELOG
        id: changelog
        run: |
          if [ -f CHANGELOG.md ]; then
            cat CHANGELOG.md > changelog.txt
          else
            echo "Sem changelog." > changelog.txt
          fi
          echo "body<<EOF" >> $GITHUB_OUTPUT
          cat changelog.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Criar Release do engine
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: "${{ steps.version.outputs.codename }} ${{ steps.version.outputs.version }}"
          body: ${{ steps.changelog.outputs.body }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
